name: tv_movie_app
description: A TV Movie streaming app similar to Apple TV+.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  video_player: ^2.8.1
  cached_network_image: ^3.3.0
  flutter_riverpod: ^2.4.9
  go_router: ^12.1.3
  http: ^1.1.0
  flutter_animate: ^4.5.0 
  hive: ^2.2.3
  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
